### ISSUE TITLE
test phone for development

### ISSUE THREAD

**Issue by Mactub07** [madsleejensen/react-native-mobilepay#1]
At first, thanks for this module. I want to ask : after integration module I can create test order and redirect to MobilePay App, but one is required paste phone to continue operation , do you know test phone (Finland) to continue operation?

**Comment by madsleejensen** [comment]
Hi, atm mobilepay only support testing by using they test merchant id's (see https://github.com/MobilePayDev/MobilePay-AppSwitch-SDK) you will have to test with your own mobilepay account but no real transactions will be made. If you need more around this please contact mobilepay :)

**Comment by Mactub07** [comment]
thanks a lot :))
