### ISSUE TITLE
multi instance for IOS in AppDelegate.m

### ISSUE THREAD

**Issue by Mactub07** [madsleejensen/react-native-mobilepay#2]
I have small trouble with adding setup in AppDelegate.m  because I have Facebook 

//Facebook Auth ----------------------------------------------------------
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  return [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}
// native Event when app go from background to foreground
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}
//Facebook Auth ----------------------------------------------------------

can you help me how compare my Facebook setup and mobilePay 

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {

  if ([[RNMobilePayHandler sharedInstance] handleMobilePayPaymentWithUrl:url]) {
    return true;
  }

  return false;
}

**Comment by madsleejensen** [comment]
Hi, the library is build with this in mind, if you look at the source code you pasted, you see its wrapped around a "if(...)" condition, it only returns true if it was handled by mobilepay. Simply replace the "return false" with your facebook code 

`return [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];`
